import './globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Toaster } from 'sonner'

import { AuthProvider } from '@/lib/context/AuthContext'

import Providers from './providers'

const pretendard = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
        <Providers>
          <AuthProvider>{children}</AuthProvider>
        </Providers>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  )
}
